#!/bin/sh
# simplest, posix sh compliant install script
set -e

install -v -m 0755 -o root -g root certbot_zimbra.sh /usr/local/bin/
mkdir -v -p /usr/local/share/man/man1
install -v -m 0644 -o root -g root  certbot_zimbra.sh.1 /usr/local/share/man/man1/

mandb
